[Settings]

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.
[build]
  publish = "dist/"
  command = "yarn build"

# Production context: All deploys from the Production branch set in your site's deploy settings will inherit these settings.
[context.production]
  publish = "dist/"

[context.deploy-preview]
  publish = "dist/"

# Branch Deploy context: All deploys that are not resulting from a Pull/Merge Request and not from the primary, linked branch will inherit these settings.
# [context.branch-deploy]
#   command = "echo branch"
# [context.branch-deploy.environment]
#   NODE_ENV = "development"


# Note that all redirects and headers are GLOBAL for all builds:
# they do not get scoped to contexts no matter where you enter them in the file
# For context-specific rules, use _headers or _redirects - those are PER-DEPLOY.
[[redirects]]
  from= "/confirmation"
  to= "/confirmation/html"

[[redirects]]
  from = "/*"
  to = "/index.html"

[[headers]]
  for = "/" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """\
                              default-src 'none';\
                              connect-src 'self' https://www.google-analytics.com www.google-analytics.com https://stats.g.doubleclick.net https://widgets.bokun.io; \
                              font-src 'self' https://fonts.gstatic.com; \
                              img-src 'self' https://www.google-analytics.com www.google-analytics.com https://stats.g.doubleclick.net https://www.paypalobjects.com; \
                              script-src 'self' https://www.googletagmanager.com https://widgets.bokun.io 'nonce-o9crONYtQ9BijkFVtg7VsA=='; \
                              style-src 'self' https://fonts.googleapis.com; \
                              frame-src 'self' https://www.youtube.com https://form.jotform.me/90283483057460 https://widgets.bokun.io; \
                              """
    Link = '''
    </assets/main.css>; rel=preload; as=style'''

[[headers]]
  for = '/assets/orange-robe-tours-project-proposal-eng.pdf'
  [headers.values]
    Conent-Security-Policy = "default-src https:"
